version: "3.9"

services:
  database:
    image: postgres
    container_name: postgres_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rental
      - POSTGRES_PASSWORD=4dmin@183
      - POSTGRES_DB=rentalcars
    volumes:
      - pgdata:/data/postgres
  

volumes:
  pgdata:
    driver: local